[project]
name = "folitools"
version = "0.2.0"
description = "Foli-seq data processing and analysis tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.85",
    "cyclopts==3.22.5",
    "ipykernel>=6.29.5",
    "ipython>=9.3.0",
    "ipywidgets>=8.1.7",
    "joblib>=1.5.1",
    "matplotlib>=3.10.3",
    "natsort>=8.4.0",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "pyarrow>=21.0.0",
    "pysam>=0.23.3",
    "scikit-learn>=1.7.0",
    "scipy>=1.16.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "umi-tools>=1.1.6",
    "wcmatch>=10.1",
]


[project.scripts]
foli = "folitools.cli:app"
foli-primer = "folitools.primer_selection.cli:app"

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
# keep local data out of built dists
wheel-exclude  = ["src/folitools/primer_selection/data/**"]
source-exclude = ["src/folitools/primer_selection/data/**"]
